### DISCUSSION TITLE
Manual update

### DISCUSSION THREAD

**Discussion by array81** [huizebruin/s0tool#225] [General]
In the past (I think about 1 year ago) I used rge s0tool code to create my Water Meter.
At the time I found the code on github but I didn't realize that it was possible to install the code with the wizard so I created an esphome device and manually added the code extrapolating it from what I found on this repository. Now update the device using the official code but I have two problems. First: I would have to update the device via wireless because its access via USB and PC is complicated. Second: if possible I would like to keep the "history" on Home Assistant, i.e. I would like HA not to notice the change and continue to see it as the same device.
Is there a way to do what is indicated? If so, how should I proceed?

Here's my code:

```
substitutions:
  name: "water-meter"
  friendly_name: "Water Meter"
  device_description: Contatore acqua

esphome:
  name: ${name}

esp8266:
  board: d1_mini
  restore_from_flash : True

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxx"
  services:
    - service: meterstand_water
      variables:
        meter_value: float
      then:
        - globals.set:
            id: initial_water_usage
            value: !lambda "return ( meter_value - (id(total_water_pulses)) * atof(id(select_pulse_water).state.c_str()) ) ;"
        - globals.set:
            id: total_water_pulses
            value:  "0"  

ota:
  password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: "xxx"

captive_portal:
    
# Enable Web server
web_server:
  port: 80
  
#  restart button  #
button:  
  - platform: restart
    name: "Restart device"
    
# Factory Reset Switch from ESPHome v2022.09    
  - platform: factory_reset
    name: Reset to factory settings   

text_sensor:
  - platform: version
    name: "ESPHome Version"

globals:
  - id: initial_water_usage
    type: float
    restore_value: yes      
    initial_value: '010' 

  - id: total_water_pulses
    type: int
    restore_value: yes
    
select:
  # water per m3 rate
  - platform: template
    name: "Pulserate water per m3"
    id: select_pulse_water
    optimistic: true
    options:
      - "0.0001"
      - "0.0005"
      - "0.001"  
      - "0.01"  
      - "0.1"                   
    initial_option: "0.001"
    restore_value: yes
    on_value:
      then:
        - logger.log:
            format: "Chosen option: %s "
            args: ["x.c_str()"]

binary_sensor:
  - platform: gpio
    id: water_sensor_status
    name: Water Proximity Sensor Status
    internal: False
    pin:
      number: D2
      inverted: true
      mode:
        input: true
    on_press:
      - then:
          lambda: id(total_water_pulses) += 1;  

  - platform: status
    name: "${friendly_name} Status"

sensor:
# watermeter pulsen
  - platform: pulse_meter #pulse_counter
    internal_filter_mode: "PULSE"
    internal_filter: 50ms  
    pin: D2
    id: watermeter_pulse_flow
    name: "Watermeter Flow"
    state_class: measurement
    unit_of_measurement: "l/min"    
    accuracy_decimals: 1
    icon: "mdi:water-pump"
    filters:
      lambda: return x * atof(id(select_pulse_water).state.c_str()) * 1000;

# Total watermeter     
    total:
      id: watermeter_pulse_meter_total
      name: "Watermeter Total"
      state_class: "total_increasing"
      device_class: water
      icon: mdi:water
      unit_of_measurement: "m³"
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
      # filters:
      #  lambda: return x * atof(id(select_pulse_water).state.c_str());

      
# Watermeter stand bij benadering
  - platform: template
    id: watermeter_total
    name: "Watermeter Stand"
    state_class: "total_increasing"
    device_class: water
    icon: mdi:water
    unit_of_measurement: "m³"
    update_interval: 30s
    accuracy_decimals: 3
    lambda: return id(initial_water_usage) + (id(total_water_pulses) * atof(id(select_pulse_water).state.c_str()));

# Waterpulses  only web interface for debugging
  - platform: template
    id: watermeter_pulse_flow_total
    name: "Watermeter Flow Total"
    state_class: "total_increasing"
    accuracy_decimals: 0
    lambda: return id(total_water_pulses);
    internal: True

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    icon: mdi:clock-outline
    update_interval: 60s
```
