### ISSUE TITLE
add initial meter total in ESPhome

### ISSUE THREAD

**Issue by stingone** [huizebruin/s0tool#156]
Could you add the option to set the initial water meter value from the meter itself into your code?

i used the code below and it works fine.

`number:
  - name: Initiële meterstand m3
    platform: template
    id: initial_water_value
    device_class: water
    min_value: 0
    max_value: 100000
    step: 0.001
    entity_category: config
    icon: mdi:water
    unit_of_measurement: "m³"
    set_action:
      - lambda: id(total_water_pulses) = x * 1000;`

**Comment by huizebruin** [comment]
Hello @stingone 

When i add this to my esphome config it stays on 0.001 and i used a lot of water today.

```yaml 
number:
  - name: Initiële meterstand m3
    platform: template
    id: initial_water_value
    device_class: water
    min_value: 0.001
    max_value: 100000
    step: 0.001
    entity_category: config
    icon: mdi:water
    unit_of_measurement: "m³"
    set_action:
      lambda: id(total_water_pulses) = x * 1000;  
      ```
      
 what did you else ?
